"""Add advertisement status

Revision ID: c1b70fa2c269
Revises: e27f27893f57
Create Date: 2025-09-14 15:33:37.249529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1b70fa2c269'
down_revision: Union[str, Sequence[str], None] = 'e27f27893f57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    advertisement_status = sa.Enum(
        'NOT_PUBLISHED',
        'AWAITING_MODERATION',
        'PUBLISHED',
        'REJECTED',
        'ARCHIVED',
        name='advertisement_status',
    )
    advertisement_status.create(op.get_bind(), checkfirst=True)

    op.add_column('advertisements', sa.Column('status', advertisement_status, nullable=False, server_default='NOT_PUBLISHED'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisements', 'status')
    # ### end Alembic commands ###